name: Deploy to AWS EKS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_BACKEND_REPO: <your-ecr-id>.dkr.ecr.us-east-1.amazonaws.com/backend
  ECR_FRONTEND_REPO: <your-ecr-id>.dkr.ecr.us-east-1.amazonaws.com/frontend
  CLUSTER_NAME: real-estate-eks

jobs:
  deploy:
    name: Build, Push & Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::<your-account-id>:role/<your-deploy-role>
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build backend Docker image
        run: |
          docker build -t $ECR_BACKEND_REPO:latest -f apps/backend/Dockerfile .
          docker push $ECR_BACKEND_REPO:latest

      - name: Build frontend Docker image
        run: |
          docker build -t $ECR_FRONTEND_REPO:latest -f apps/frontend/Dockerfile .
          docker push $ECR_FRONTEND_REPO:latest

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION

      - name: Set up Pulumi
        uses: pulumi/actions@v4
        with:
          command: up
          stack-name: dev
          work-dir: apps/infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
